# https://starship.rs/config/#command-duration

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $swift\
  $rust\
  $ruby\
  $python\
  $nodejs\
  $kotlin\
  $golang\
  $elixir\
  $dart\
  $nix_shell\
  $conda\
  $memory_usage\
  $nix_shell\
  $custom\
  $line_break\
  $jobs\
  $time\
  $battery\
  $character\
  """

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"
vicmd_symbol = "[â®](bold green)"

[git_branch]
symbol = ""

[git_commit]
tag_disabled = false

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "â•"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[directory]
truncation_length = 8
truncate_to_repo = false
fish_style_pwd_dir_length = 4

[swift]
format = "[SWIFT $version](bold purple) "

[rust]
format = "[RUST $version](bold purple) "

[ruby]
format = "[RUBY $version](bold red) "

[python]
format = "[PYTHON $version](bold purple) "

[nodejs]
format = "[NODE $version](bold yellow) "

[kotlin]
format = "[KOTLIN $version](bold purple) "

[golang]
format = "[GO $version](bold purple) "

[elixir]
format = "[ELIXIR $version](bold purple) "

[dart]
format = "[DART $version](bold purple) "
